# .streamlit/secrets.toml
[signatures]
ceo = "firmas/ceo_signature.png"    # Ruta relativa a la firma del CEO
 # Firma del Gerente General

[stripe]
public_key = "pk_test_tu_key_publica"
secret_key = "sk_test_tu_key_secreta"

# .streamlit/secrets.toml
[smtp]
server = "smtp.gmail.com"
port = 587
user = "tucorreo@gmail.com"
password = "tu_contraseña_app"
