# .streamlit/secrets.toml
[signatures]
[signatures]
CEO = "your_ceo_signature_value"    # Ruta relativa a la firma del CEO
gerente_general = "firmas/gerente_signature.png"  # Firma del Gerente General

[smtp]
server = "smtp.gmail.com"                # Servidor SMTP
port = 587                               # Puerto seguro
user = "tucorreo@gmail.com"              # Email de envío
password = "contraseña_o_app_password"   # Contraseña de aplicación*

[stripe]
public_key = "pk_test_tu_key_publica"
secret_key = "sk_test_tu_key_secreta"
