# .streamlit/secrets.toml
[smtp]
server = "smtp.tudominio.com"  # Ej: smtp.gmail.com
port = 587                      # Puerto SMTP
user = "tucorreo@empresa.com"
password = "tu_contraseña_app"  # Contraseña de aplicación

[signatures]
ceo = "firmas/ceo_signature.png"
gerente_general = "firmas/gerente_signature.png"

[stripe]
public_key = "pk_test_tu_key_publica"
secret_key = "sk_test_tu_key_secreta"
