# .streamlit/secrets.toml
[signatures]
ceo = "firmas/ceo_signature.png"    # Ruta relativa a la firma del CEO
 # Firma del Gerente General

[smtp]
server = "https://enterpriseflow.streamlit.app/"                # Servidor SMTP
port = 587                               # Puerto seguro
user = "marinyferreyra@outlook.com"              # Email de envío
password = "LosDeAI99+"   # Contraseña de aplicación*

[stripe]
public_key = "pk_test_tu_key_publica"
secret_key = "sk_test_tu_key_secreta"
